// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileNode represents a file or directory in the file explorer.
 */
export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {(FileNode | null)[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

/**
 * ProjectRecord stores a named project with its disk path.
 */
export class ProjectRecord {
    /**
     * Creates a new ProjectRecord instance.
     * @param {Partial<ProjectRecord>} [$$source = {}] - The source object to create the ProjectRecord.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectRecord(/** @type {Partial<ProjectRecord>} */($$parsedSource));
    }
}

/**
 * SnapshotData represents the full payload for the frontend
 */
export class SnapshotData {
    /**
     * Creates a new SnapshotData instance.
     * @param {Partial<SnapshotData>} [$$source = {}] - The source object to create the SnapshotData.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("pdfBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pdfBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotData(/** @type {Partial<SnapshotData>} */($$parsedSource));
    }
}

export class SnapshotMeta {
    /**
     * Creates a new SnapshotMeta instance.
     * @param {Partial<SnapshotMeta>} [$$source = {}] - The source object to create the SnapshotMeta.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotMeta(/** @type {Partial<SnapshotMeta>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
