// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function CreateBlankProject(path) {
    return $Call.ByID(3671670566, path);
}

/**
 * @param {string} dirPath
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function CreateEmptyFile(dirPath, filename) {
    return $Call.ByID(653204180, dirPath, filename);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(path) {
    return $Call.ByID(2368348335, path);
}

/**
 * GetCurrentProject returns the currently tracked project directory.
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentProject() {
    return $Call.ByID(158434009);
}

/**
 * @returns {$CancellablePromise<$models.ProjectRecord[]>}
 */
export function GetProjects() {
    return $Call.ByID(3930076657).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportFile picks a file and copies it to the project path.
 * @param {string} targetDir
 * @returns {$CancellablePromise<void>}
 */
export function ImportFile(targetDir) {
    return $Call.ByID(1694890310, targetDir);
}

/**
 * ImportProjectFromZip creates a new project from a selected zip file.
 * @param {string} projectName
 * @param {string} targetBaseDir
 * @returns {$CancellablePromise<$models.ProjectRecord | null>}
 */
export function ImportProjectFromZip(projectName, targetBaseDir) {
    return $Call.ByID(1463618708, projectName, targetBaseDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ImportZip picks a zip and extracts it to the project path.
 * @param {string} targetDir
 * @returns {$CancellablePromise<void>}
 */
export function ImportZip(targetDir) {
    return $Call.ByID(4135890847, targetDir);
}

/**
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.FileNode | null>}
 */
export function ListFiles(dirPath) {
    return $Call.ByID(127973248, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PickDirectory opens a native OS dialog to select a folder and returns the path.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory(title) {
    return $Call.ByID(2303833303, title);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(935978095, path);
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveFile(path, content) {
    return $Call.ByID(3545576426, path, content);
}

/**
 * SaveImageAsset writes a base64-encoded image from the frontend into <projectPath>/assets/.
 * Returns the relative path usable in \includegraphics (e.g. "assets/photo.png").
 * @param {string} projectPath
 * @param {string} filename
 * @param {string} base64Data
 * @returns {$CancellablePromise<string>}
 */
export function SaveImageAsset(projectPath, filename, base64Data) {
    return $Call.ByID(613072743, projectPath, filename, base64Data);
}

/**
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveProject(name, path) {
    return $Call.ByID(3939961329, name, path);
}

/**
 * SetCurrentProject sets the active project directory.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentProject(path) {
    return $Call.ByID(3896130677, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateProject(path) {
    return $Call.ByID(467615428, path);
}

// Private type creation functions
const $$createType0 = $models.ProjectRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
const $$createType3 = $models.FileNode.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
