// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateBlankProject creates the directory and scaffolds a main.tex inside.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function CreateBlankProject(path) {
    return $Call.ByID(3671670566, path);
}

/**
 * CreateEmptyFile creates a blank file inside the project.
 * For .tex files, a minimal LaTeX boilerplate is written instead of empty content.
 * @param {string} dirPath
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function CreateEmptyFile(dirPath, filename) {
    return $Call.ByID(653204180, dirPath, filename);
}

/**
 * DeleteProject removes a project from the saved list by path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(path) {
    return $Call.ByID(2368348335, path);
}

/**
 * GetCurrentProject returns the currently tracked project directory.
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentProject() {
    return $Call.ByID(158434009);
}

/**
 * GetProjects returns all saved projects.
 * @returns {$CancellablePromise<$models.ProjectRecord[]>}
 */
export function GetProjects() {
    return $Call.ByID(3930076657).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListFiles returns the file tree of the given directory.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.FileNode | null>}
 */
export function ListFiles(dirPath) {
    return $Call.ByID(127973248, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PickDirectory opens a native OS dialog to select a folder and returns the path.
 * Returns an empty string if cancelled.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory(title) {
    return $Call.ByID(2303833303, title);
}

/**
 * ReadFile reads a file from the filesystem.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(935978095, path);
}

/**
 * SaveFile saves text content to the filesystem.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveFile(path, content) {
    return $Call.ByID(3545576426, path, content);
}

/**
 * SaveProject saves/updates a named project record to the projects list.
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveProject(name, path) {
    return $Call.ByID(3939961329, name, path);
}

/**
 * SetCurrentProject sets the active project directory (does NOT persist automatically).
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentProject(path) {
    return $Call.ByID(3896130677, path);
}

/**
 * ValidateProject checks if a given directory path exists.
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateProject(path) {
    return $Call.ByID(467615428, path);
}

// Private type creation functions
const $$createType0 = $models.ProjectRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FileNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
