// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSnapshot takes the current active file and its compiled PDF and saves a snapshot.
 * @param {string} projectPath
 * @param {string} activeFilePath
 * @param {string} label
 * @param {string} pdfBase64
 * @returns {$CancellablePromise<$models.SnapshotMeta | null>}
 */
export function CreateSnapshot(projectPath, activeFilePath, label, pdfBase64) {
    return $Call.ByID(2948561629, projectPath, activeFilePath, label, pdfBase64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} snapshotID
 * @returns {$CancellablePromise<$models.SnapshotData | null>}
 */
export function GetSnapshotData(projectPath, snapshotID) {
    return $Call.ByID(3455690447, projectPath, snapshotID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.SnapshotMeta[]>}
 */
export function GetSnapshots(projectPath) {
    return $Call.ByID(3979602396, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} activeFilePath
 * @param {string} snapshotID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreSnapshot(projectPath, activeFilePath, snapshotID) {
    return $Call.ByID(2243995641, projectPath, activeFilePath, snapshotID);
}

// Private type creation functions
const $$createType0 = $models.SnapshotMeta.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SnapshotData.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
