// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ASTNode is the flat/JSON-friendly representation we send to the frontend.
 */
export class ASTNode {
    /**
     * Creates a new ASTNode instance.
     * @param {Partial<ASTNode>} [$$source = {}] - The source object to create the ASTNode.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * e.g. "InlineMath", "Section", "Label", "BindTag"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * The raw matched string or extracted argument
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * 1-indexed
             * @member
             * @type {number}
             */
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            /**
             * 1-indexed
             * @member
             * @type {number}
             */
            this["column"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ASTNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ASTNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ASTNode(/** @type {Partial<ASTNode>} */($$parsedSource));
    }
}
