// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service for AST parsing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Parse digests the raw LaTeX string and returns a list of semantic AST nodes
 * intended to power CodeMirror decorations (Ghost Previews) and Data Binding.
 * @param {string} source
 * @returns {$CancellablePromise<$models.ASTNode[]>}
 */
export function Parse(source) {
    return $Call.ByID(3158234981, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ASTNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
