// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearCache removes the Tectonic cache on Windows, forcing a fresh package download.
 * @returns {$CancellablePromise<void>}
 */
export function ClearCache() {
    return $Call.ByID(4172808486);
}

/**
 * Compile compiles the given .tex file with Tectonic and returns the result.
 * @param {string} activeFilePath
 * @returns {$CancellablePromise<$models.CompileResult | null>}
 */
export function Compile(activeFilePath) {
    return $Call.ByID(1429634592, activeFilePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CompileResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
