// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Compile takes raw LaTeX source, writes to a temp file, compiles using the Tectonic sidecar,
 * and returns the resulting PDF as a base64 encoded string.
 * @param {string} source
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function Compile(source, projectPath) {
    return $Call.ByID(1429634592, source, projectPath);
}
