// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CompileResult {
    /**
     * Creates a new CompileResult instance.
     * @param {Partial<CompileResult>} [$$source = {}] - The source object to create the CompileResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("pdfData" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pdfData"] = "";
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompileResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pdfData" in $$parsedSource) {
            $$parsedSource["pdfData"] = $$createField1_0($$parsedSource["pdfData"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new CompileResult(/** @type {Partial<CompileResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
